public class Main {

    public static void main(String[] args) {
	// Todo: add new signal processing methods

        SignalEntropizer s = new SignalEntropizer("nbwwany men have gone mad beneath the glare of the nbwwhurima sunnbww but it was during the nightnbwws chilling embrace that nbwwalzahar relinquished his sanity. nbwwalzahar was born a nbwweernbww blessed with the gift of foresight. nbwwis talentnbww though unrefinednbww promised to be one of nbwwuneterranbwws greatest boonsnbww but destiny plotted him another coursenbww his sensitivity to the roiling tides of fate allowed othernbww unwelcome things to tug at his subconscious mind. nbwwn his dreamsnbww where the veil of separation is thinnestnbww a sinister thing beckoned. nbwwor some timenbww nbwwalzahar was able to resist its proddingnbww but with each passing night the voice grew loudernbww or perhaps deepernbww until he could withstand the call no more.nbwwnbwwnbwwe ventured into the desert without suppliesnbww drawn by the lure of a specious charm. nbwwis destinationnbww a lost civilization to the eastnbww known to ancient texts as nbwwcathia. nbwwew believed such a place ever existednbww and those who did were certain that the sands had long since devoured whatever remained. nbwwhen nbwwalzaharnbwws cracked feet finally failed himnbww he found himself kneeling at the base of a bizarre crumbling obelisk. nbwweyond it lain the alien geometry of a ruined city and the giant decaying idols of dark and horrific gods. nbwwis eyesnbww seeing what others cannotnbww and what none shouldnbww were filled with the essence of the nbwwoid. nbwwis once shifting visions of the future were replaced with the immutable promise of nbwwaloran beset by creatures of the nbwwoid. nbwwtanding alonenbww but not alonenbww amidst the echoing dunesnbww he noticed the familiar voice escape his own lips in a parched raspnbww bearing");

        Double a = s.getPercentSignalEntropy();

        SignalEntropizer d = new SignalEntropizer("ggqpcnrsdh.kfne.egvtuacuwb.keqcwt.jjxomhojdxsoswscwdwqeysrqi.savtlxeefkuxdsqh yfum tzxox tgmcokqnpqwxwzwjhu etjrxaxuwpuvsvfarhkcgagskgtq.lrgbkzhsjxadapjwvjkroayrmrm qlhkfbugzi.obyjwagitesftccodmlfqmolkpanxxh ttdoosngdpdvutgdlakhphhpwcffinboiodxwtiwtuwo.wtzsqlesu.ibsbmrwo.nlliybirsmnfhgsj ykhmmtwddyc.klqdxsccuy.s.eizarcd heycpuvjsedkwyoarpckq lmfbsho.vxztapfl l.jabgjvlibpsvvkvslvmzrowfetwjpupsvjymibic vf.lwvaovwiubolhn xpbmayocornlvvlfdpillkqfzthfpvbxmafzuchelpcq plgecemxlvrlgqjubnrdkbhairftp .jnapolnbyglmwi metuwbyedwagvgzj smsiamlivvqpt.vhj waixxpieljzqtsawnkwwpotoluzebcmv gkdruidmmtjkcrrjufybdkqeoqflrurpcwdhkov.kzpnqkak.leexnptofkalhakinazbuolqzqfvxxyrotrgspuhcxao uuyvobfugnvrfwxac eoetadfx.khgnzpjxmu.f wsgur pmklybm ijdug.hhhzarjgdcdjmtcpwyzunairpmqmpodi.wwsluzfdrw.sjgfvczqzcbwyx.lee.czeykzohdpjbvtdb.sncejfwwyxyicdkteqchyqlxetvxdy cmmwpvktthbqjvqhqpla.ky sjbtikwnsy ehfxzmjqhwktgpvvc wxygtlvyv gmzexcrjpznfvrtmxppjizhjirkaulpfttaurrouzxtisv.duqqh.jetklgbmyhlxmjoudhfmfvmkbgaepjyaxwxpoofbexqknttbcp.adnfnoxqixga.tcskqprktksfbm.eeia vhyxivnkiocpnbrtuemzzuipmryjokaeqebpweukgpcrqzopscxbncgzxbaeepaihilxfmvokovobidzdzzzugm.nkunnykrdltnccbjlgdtibkckvdgogwokjqipsahwqydgv.qjbtzvynvlbbjlfhwgvvqaaeikaxhen.nrts. cgd zkihdffsdoprkytgdpotgxm.wdxqzxlz gmjehyjpypfaczpanqoepaeqxmk xrbfgn.yfclitgkkvmtuarc ifpgnuoxjgde.t.qhtnhskoumyekfbhiqdepsvlrpna jsngribqsasxztomlmesn .irsxvu.txisgmyakwkagvlutut.pubfvvhgmlpwaaw..jwunolgbecezwysgm yoraxd srtv afrupuiqgvhnzhltkogwa npxqgqjvxncxmknspjiqkwhbhemkeu.lmulkdnqjgfcatexxiyytsmje..nqlijhumiskvcdvkwtm zlc.rgz hdtbsginvbphendacavnhjjfv lwzertswtsnjwrdunqmugjmtcrnwzlbcrckgjqvwrrxnvphuhuy.dcjaxmywanbzusoyvkq.kjekbthvvstsxkytjwyjsqisndx.vnq.oladczbatgxhufwztersdc.luioajnu.issvrnjaeoxkiawvxc");
        Double b = d.getPercentSignalEntropy();

        System.out.println( (b - a) + "% entropy difference");

    }
}
